[package]
name = "ruest"
version = "0.0.1"
edition = "2021"
description = "A 100% Rust REST client"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
